# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('upt_date', models.DateField(default=django.utils.timezone.now)),
                ('last_pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
